rudderlabs/rudder-sdk-kotlin

.github/workflows/release.yml, CHANGELOG.md, gradle/publishing/publishing.gradle.kts
- Added `releasse.yml` github action to release the version through GitHub actions.
- Use different signature extensions function.
- Add changelog.md
> Fix [#1]()
=> ci: add release.yml, changelog.md and change signature extension

scripts/commit-msg
- We've updated the commit hook (which detects if the commit title follows the conventional commit).
- Some compatibility issues were observed with our global pre-commit hook. So, we made an optimisation in our script to fix that.
- After setting up the global pre-commit hook and running this `git config --local --unset core.hooksPath`. It was causing some issues:
- After investigating further, found that, this `$(cat $1)` was not detecting this file `.git/COMMIT_EDITMSG`. Due to this the commit title was blank and this pre-commit hook was failing even though the commit title was proper.
- Note: This file contains the commit title.
- We improved this hook to directly refer to the correct file i.e., `.git/COMMIT_EDITMSG`.
1. Clone or checkout to this PR branch.
2. Remove the hook folder to …
=> chore: update commit hook

build.gradle.kts, gradle/publishing/publishing.gradle.kts
- Removed debug statement from the release script.
- Removed `println` statement from the `gradle` files.
=> chore: remove debug statements from release script

integrations/adjust/src/main/java/com/rudderstack/integration/kotlin/adjust/AdjustIntegration.kt, integrations/adjust/src/test/java/com/rudderstack/integration/kotlin/adjust/AdjustIntegrationTest.kt
- I noticed that even if the log level is set to Verbose the Adjust environment is not being set to sandbox because this `logLevel >= Logger.LogLevel.DEBUG` is not giving the desired result.
- I refactored the logic to check if the log level is NONE then set the Adjust environment to production else sandbox.
- Replaced `addGlobalCallbackParameter` with `addGlobalPartnerParameter`.
- Fixed the logic where we are comparing the log level and setting the Adjust environment.
- Fixed the `setSessionParams` to use the correct `addGlobalPartnerParameter` API. Also, updated the corresponding test cases.
- Set the log level to verbose, debug, info etc. and notice that Adjust environment will be set to sandbox.
- Set the log level to NONE and notice that Adjust environment will be set to production.
=> fix: set proper adjust environment and use addGlobalPartnerParameter API

integrations/adjust/src/test/java/com/rudderstack/integration/kotlin/adjust/AdjustIntegrationTest.kt
The recent PR on ExternalId contained some breaking changes. This PR is to remove the usage of externalId from the AdjustIntegration test cases
- Removed the usage of the externalId from the AdjustIntegration test case.
Run `./gradlew test`.
If you're merging/checking out from develop then ensure to cherry pick this commit.
=> fix: remove unused externalIds parameter from AdjustIntegration test

integrations/adjust/src/main/java/com/rudderstack/integration/kotlin/adjust/AdjustIntegration.kt, integrations/adjust/src/main/java/com/rudderstack/integration/kotlin/adjust/Utils.kt, integrations/adjust/src/test/java/com/rudderstack/integration/kotlin/adjust/AdjustIntegrationTest.kt
Handle an edge case in the Adjust integration where the config is an empty JSON object. Previously this was causing an exception.
- In the Adjust integration, check if the config is an empty JSON object before attempting to parse it. 
- If it's an empty JSON object log the appropriate message and then return null.
- In the dashboard don't connect the Adjust integration to the Android source.
- While initialising the SDK ensure to add the Adjust integration.
- Run the app and you shouldn't observe any error related to the Adjust integration.
Now we are logging this message if the config object is empty:
We also have an option of not updating the integration config in case of failure.
=> fix: handle empty configuration in parseConfig method for Adjust integration

android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/connectivity/AndroidConnectivityObserverPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/AndroidLifecyclePlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/DeeplinkPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/devicemode/IntegrationPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/devicemode/IntegrationsManagementPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/lifecyclemanagment/ActivityLifecycleManagementPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/lifecyclemanagment/ProcessLifecycleManagementPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/screenrecording/ActivityTrackingPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/screenrecording/NavControllerTrackingPlugin.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/plugins/Plugin.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/plugins/PluginChain.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/plugins/RudderStackDataplanePlugin.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/plugins/PluginChainTest.kt
This PR updates the `PluginType` enum. It changes the `Manual` and `Destination` type to `Utility` and `Terminal` respectively. It also removes the unused `After` PluginType.
=>  refactor: update plugin types

android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/Analytics.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/connectivity/AndroidConnectivityObserverPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/screenrecording/NavControllerTrackingPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionState.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionTrackingPlugin.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/state/NavContext.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/AndroidConnectivityObserverTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/devicemode/IntegrationsManagementPluginTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/devicemode/eventprocessing/EventFilteringPluginTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/screenrecording/NavControllerActivityObserverTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/screenrecording/NavControllerTrackingPluginTest.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/Analytics.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/AnalyticsConfiguration.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/SourceConfigManager.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/models/SourceConfig.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/models/connectivity/ConnectivityState.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/models/useridentity/UserIdentity.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/statemanagement/State.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/statemanagement/StateAction.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/SourceConfigManagerTest.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/models/SourceConfigTest.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/statemanagement/StateTest.kt
In this PR, we rename `FlowState` to `State` and `FlowAction` to `StateAction`.
=> refactor: rename flow state and flow action

android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/Analytics.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionInfo.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionManager.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionTrackingObserver.kt, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionTrackingPlugin.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionInfoTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionManagerTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionTrackingObserverTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/sessiontracking/SessionTrackingPluginTest.kt
In this PR, broadly, we refactor `SessionTrackingPlugin` to break it down into two classes - `SessionTrackingPlugin` and `SessionManager`.
- `SessionManager` class is created. It is responsible for handling session variables, updating them in storage and exposing the methods to modify them from `Analytics` class which in turn expose them as public APIs.
- `SessionTrackingPlugin` is now only responsible for attaching session variables to the payload. It does that by maintaining an instance of `SessionManager` inside it.
- The `getSessionId` API is changed to `sessionId` in `Analytics`.
- A logic for detaching the `SessionTrackingObserver` is added in `SessionManager` when `endSession` is called or `startSession` is called for manual session (we don't want any observer for manual session). …
=> refactor: SessionTrackingPlugin

android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/AnalyticsTest.kt
We have added unit tests for the Android Anlaytics class.
- Added unit tests to verify the following behaviours:
- SessionId API's, including manual session API and sessionId.
- Effect of Reset and Shutdown on sessionId API.
- Again added the custom plugin test, as we've overridden this API.
- Added test for verifying Android log level.
We haven't introduced any features. Just added test cases.
NOTE: I've intentionally omitted a few of the tests, as those tests will require refactoring of the Analytics class to make them unit testable, e.g., we cannot verify if all the plugins are added in the chain or if integrationManagementPlugin adds the terminal type of plugin.
=> test: add unit test for android Analytics class

.github/workflows/lint.yml, integrations/braze/src/test/java/com/rudderstack/integration/kotlin/braze/BrazeIntegrationTest.kt, integrations/braze/src/test/java/com/rudderstack/integration/kotlin/braze/Utility.kt, integrations/braze/src/test/java/com/rudderstack/integration/kotlin/braze/UtilsTest.kt
> In this PR we are updating the Github actions by removing the `cancel-workflow-action `. At the same time, we identified an issue in a utility file that was causing 3 test to fail as well as blocking the push of the branch to develop. The fix was been introduced in this PR as well.
> Fix [#1]()
=> chore: update GitHub actions

app/src/main/java/com/rudderstack/sampleapp/analytics/RudderAnalyticsUtils.kt, app/src/main/java/com/rudderstack/sampleapp/analytics/customplugins/OptionPlugin.kt, app/src/main/java/com/rudderstack/sampleapp/analytics/customplugins/SetAnonymousIdPlugin.kt, app/src/main/java/com/rudderstack/sampleapp/analytics/customplugins/SetDeviceTokenPlugin.kt, app/src/test/kotlin/com/rudderstack/sampleapp/analytics/customplugins/OptionPluginTest.kt, app/src/test/kotlin/com/rudderstack/sampleapp/analytics/customplugins/SetDeviceTokenPluginTest.kt
- We have added the option to set externalId globally.
- Added documentation for `SetAnonymousIdPlugin`.
- Added `SetDeviceTokenPlugin` custom plugin to set device token.
- Removed the setting of `OptionPlugins` in the sample app. I've provided the instructions in the Plugin doc.
- We've added an option to set the externalId. If this value is already present in the event then it'll be merged and the global value will take higher preference.
- Added and updated test cases.
- Add these plugins just after SDK initialisation:
```
// OptionPlugin: It supports customContext, integrations and externalId
analytics.add(
GlobalRudderOptionPlugin(
option = RudderOption(
customContext = buildJsonObject { put("key", "value") },
integrations = buildJsonObject { put("CleverTap", true) },
externalIds = …
```
=> chore: add custom plugins

android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/logger/AndroidLogger.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/logger/KotlinLogger.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/logger/Logger.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/logger/LoggerAnalytics.kt
In this PR, we update the `Logger` interface to remove the `setTag` method and also remove the global `TAG` variable.
The role of `setTag` method was ambiguous - if a client overrides it in their custom `Logger` implementation, they cannot do anything with it. The responsibility of setting of tag should lie with the implementor of the `Logger` interface, therefore we remove the global `TAG` and the `setTag` method.
All the logs should be printed same as before.
=> refactor: logger

app/src/main/java/com/rudderstack/sampleapp/analytics/customplugins/AndroidAdvertisingIdPlugin.kt, app/src/main/java/com/rudderstack/sampleapp/analytics/customplugins/SetAnonymousIdPlugin.kt, app/src/main/java/com/rudderstack/sampleapp/analytics/customplugins/SetPushTokenPlugin.kt, app/src/test/kotlin/com/rudderstack/sampleapp/analytics/customplugins/SetPushTokenPluginTest.kt
- Changed from `SetDeviceTokenPlugin` to `SetPushTokenPlugin`. This is done for clarity.
- In the custom plugins, the exact location where this value is set has been specified for clarity.
- Changed from `PreProcess` to `OnProcess` for custom plugins.
- Added doc for `AndroidAdvertisingIdPlugin`.
- The user needs to change `SetDeviceTokenPlugin` to `SetPushTokenPlugin`.
- The plugin type was changed from `PreProcess` to `OnProcess` to ensure the payload is properly constructed before the user modifies it.
- Currently, the SDK cannot guarantee that the payload schema remains intact due to the use of custom plugins.
- Adding any custom plugins places them at the bottom of the plugin chain. These custom plugins are executed only after all standard plugins, meaning there is no difference …
=> chore: update custom plugins

android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/Analytics.kt
Removed the experimental annotation from the `setNavigationDestinationsTracking` public API.
This PR doesn't contain any feature / fix. So no test is required.
=> chore: remove experimental annotation from the screen tracking api

core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/policies/backoff/BackOffPolicy.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/policies/backoff/ExponentialBackOffPolicy.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/policies/backoff/ExponentialBackOffPolicyTest.kt
This PR adds a new policy called `BackOffPolicy` and provides its implementation called `ExponentialBackOffPolicy`.
The `BackOffPolicy` has below methods:
- `nextDelayInMillis` - it provides the next delay in milliseconds for a given backOff policy.
- `resetBackOff` - it reset the given instance of policy to the initial state.
The `ExponentialBackOffPolicy` implements this interface and provides the delays which are increasing an exponential fashion. 
`delay = interval * base ^ attempt`
Here, `attempt` is number of times the method `nextDelayInMillis` is called. `resetBackOff` resets this value to zero again.
=> feat: add exponential backoff

core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/queue/EventQueue.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/queue/EventUpload.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/queue/EventQueueTest.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/queue/EventUploadTest.kt
I've refactored the `EventQueue` class by moving the `upload` related logic to a new `EventUpload` class. This is to ensure we can develop the `write` and `upload` features independently and provide better maintainability support. 
(In the next PR, we are expecting to add some new features in the upload, and this would have increased the no. of methods in the EventQueue class, and it would also be hard to maintain this. That's why it became necessary.)
NOTE: This new `EventUpload` class is internally used by the `EventQueue` class. The flow of events (i.e., writing and uploading) is intact.
- EventQueue.start -> EventUpload.start
- EventQueue.stop -> EventUpload.cancel
- EventQueue.uploadChannel.trySend(UPLOAD_SIG) -> EventUpload.flush
- EventQueue.upload -> EventUpload.upload
- …
=> refactor: create a new EventUpload class to handle the upload logic separately

core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/SourceConfigManager.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/SourceConfigManagerTest.kt
This PR adds delete functionality (deleting of incorrect events file made with the wrong writeKey) on 400 response code of `/sourceConfig` API.
Replaced the `shotudown` method in 400 response code for `/sourceConfig` with `analytics.handleInvalidWriteKey()`.
Refer to [this](https://github.com/rudderlabs/rudder-sdk-kotlin/pull/147) PR for more details.
=> refactor: implement delete events for invalid write key response of sourceConfig

android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/plugins/devicemode/IntegrationPlugin.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/devicemode/CustomIntegrationPluginTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/plugins/devicemode/StandardIntegrationPluginTest.kt
This PR refactors the `update` API in `IntegrationPlugin` to make its calling safe and to be called only in the subsequent emissions of `sourceConfig`.
Following changes are done:
1. The `update` method was previously being called without a `try` `catch` block - is now wrapped in a try catch block.
2. For the initial `sourceConfig` both `create` and `update` were being called which is not desirable. We only want to update a destination if it is already initialised. This is being fixed.
3. Method nomenclature and structuring are improved in `IntegrationPlugin` class.
4. All the previous logic is intact and therefore all the previous tests are passing as is. New tests are added for testing the `update` method related changes in `StandardIntegrationPluginTest` and …
=> fix: update method to make it safe

app/src/main/java/com/rudderstack/sampleapp/analytics/RudderAnalyticsUtils.kt, gradle/libs.versions.toml, integrations/braze/src/main/java/com/rudderstack/integration/kotlin/braze/BrazeIntegration.kt, integrations/braze/src/main/java/com/rudderstack/integration/kotlin/braze/RudderBrazeConfig.kt
This PR adds missing `US-07` region and new `AU-01` region for braze data center endpoint mapping. It also updates Braze sdk version to `35.0.0`.
Following changes are done:
1. Braze SDK is updated from `34.0.0` to `35.0.0`.
2. Missing region `US-07` is added.
3. New region `AU-01` is added.
Changes made are then tested by checking that events are reaching `Braze` dashboard.
=> feat: add AU-01 & US-07 region support and update Braze

android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/connectivity/AndroidConnectivityObserverPlugin.kt, buildSrc/src/main/kotlin/RudderStackBuildConfig.kt
- Bump the SDK version to `1.0.0`.
- Suppress missing permission: `android. permission. ACCESS_NETWORK_STATE`.
=> chore: prepare the SDK for v1.0.0

android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/AnalyticsTest.kt, android/src/test/kotlin/com/rudderstack/sdk/kotlin/android/utils/Utils.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/Analytics.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/AnalyticsConfiguration.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/SourceConfigManager.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/models/useridentity/SetUserIdAndTraitsAction.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/policies/FrequencyFlushPolicy.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/queue/EventQueue.kt, core/src/main/kotlin/com/rudderstack/sdk/kotlin/core/internals/queue/EventUpload.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/AnalyticsTest.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/Utils.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/models/useridentity/SetUserIdAndTraitsActionTest.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/policies/FrequencyFlushPolicyTest.kt, core/src/test/kotlin/com/rudderstack/sdk/kotlin/core/internals/utils/AnalyticsUtilTest.kt, integrations/facebook/src/test/kotlin/com/rudderstack/integration/kotlin/facebook/TestUtils.kt, integrations/firebase/src/test/kotlin/com/rudderstack/integration/kotlin/firebase/TestUtils.kt
- Pull release chagnes.
- ...
- ...
=> chore: pull release v1.0.0 changes

README.md
=> chore: remove alpha label from readme

README.md
=> chore: pull readme changes into main

android/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/RudderStackBuildConfig.kt, core/build.gradle.kts, gradle/libs.versions.toml, gradle/publishing/publishing.gradle.kts, gradle/publishing/publishing.integration.gradle.kts, integrations/adjust/build.gradle.kts, integrations/braze/build.gradle.kts, integrations/facebook/build.gradle.kts, integrations/firebase/build.gradle.kts
- In this PR, we've prepared all the integrations modules for release.
- Improve the publishing script and `RudderStackBuildConfig.kt`.
- Steps to release the snapshot version for all the modules including Android/Core & integrations:
```
clear && ./gradlew publishToSonatype
```
**NOTE: This will attempt to release all the modules.**
- Steps to release individual integration modules:
```
clear && ./gradlew :integrations:adjust:publishToSonatype 
clear && ./gradlew :integrations:braze:publishToSonatype 
clear && ./gradlew :integrations:facebook:publishToSonatype 
clear && ./gradlew :integrations:firebase:publishToSonatype 
```
- Steps to release Android and core modules:
```
clear && ./gradlew :android:publishToSonatype :core:publishToSonatype
```
- Now, all the integration modules depend …
=> chore: prepare integration modules for releases

README.md, android/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/RudderStackBuildConfig.kt, core/build.gradle.kts, gradle/libs.versions.toml, gradle/publishing/publishing.integration.gradle.kts, integrations/adjust/README.md, integrations/adjust/build.gradle.kts, integrations/braze/README.md, integrations/braze/build.gradle.kts, integrations/facebook/README.md, integrations/facebook/build.gradle.kts, integrations/firebase/README.md, integrations/firebase/build.gradle.kts, integrations/firebase/src/main/kotlin/com/rudderstack/integration/kotlin/firebase/FirebaseIntegration.kt, integrations/firebase/src/main/kotlin/com/rudderstack/integration/kotlin/firebase/Utils.kt, integrations/firebase/src/test/kotlin/com/rudderstack/integration/kotlin/firebase/FirebaseIntegrationTest.kt, integrations/firebase/src/test/kotlin/com/rudderstack/integration/kotlin/firebase/UtilsTest.kt
Release the first version (1.0.0) for the following Kotlin integrations:
1. Adjust
2. Braze
3. Facebook
4. Firebase
- Added and updated Readme files.
=> chore: release all kotlin integrations

README.md, integrations/adjust/README.md, integrations/braze/README.md, integrations/facebook/README.md, integrations/firebase/README.md
=> chore: pull release changes

.github/workflows/branch_validation.yml, android/src/main/kotlin/com/rudderstack/sdk/kotlin/android/connectivity/AndroidConnectivityObserverPlugin.kt, sonar-project.properties
This pull request adds CI/CD improvements to enhance the project's quality assurance and code validation processes. It introduces a branch validation workflow that runs automated checks on all branches (except main) and configures SonarCloud integration for code quality analysis.
- Added `.github/workflows/branch_validation.yml` to implement automated validation for all branches
- Runs Detekt static code analysis on affected modules
- Performs Android Lint checks on affected modules
- Executes SonarCloud analysis for code quality metrics
- Runs unit tests on affected modules
- Builds affected modules to ensure compilation success
- Uploads test reports as artifacts for easier debugging
- Sends Slack notifications with validation results
- Added `sonar-project.properties` to configure …
=> feat: android implement android branch validation workflow

.github/workflows/pr-validation.yml
This PR introduces a comprehensive PR Validation workflow (`pr-validation.yml`) that automatically validates pull requests targeting the develop branch and feature branches (`feat/*`). The workflow ensures code quality, runs tests, and builds artifacts for affected modules before allowing PRs to be merged.
This addresses the need for automated quality gates in our CI/CD pipeline and replaces manual validation steps with automated checks that run on every PR.
The PR validation workflow includes the following key features:
- **Semantic PR Title Validation**: Enforces conventional commit format for PR titles (feat, fix, docs, chore, refactor, test, ci)
- **Smart Module Detection**: Automatically detects which modules (core, android, integrations/*) are affected by changes
- **Targeted …
=> feat: create pr-validation.yml

integrations/facebook/src/main/kotlin/com/rudderstack/integration/kotlin/facebook/FacebookIntegration.kt, integrations/facebook/src/test/kotlin/com/rudderstack/integration/kotlin/facebook/FacebookIntegrationTest.kt
This pull request updates the `FacebookIntegration` module to align with the naming conventions used by Facebook's API. Specifically, it changes the key `dateOfBirth` to `birthday` in both the integration logic and its corresponding test cases. This is done to align as per the old [Facebook integration](https://github.com/rudderlabs/rudder-integration-facebook-android) in java.
* [`integrations/facebook/src/main/kotlin/com/rudderstack/integration/kotlin/facebook/FacebookIntegration.kt`](diffhunk://#diff-341de0dde78addae8ee86a370fdec158527bafed0d016a3b69442b49f9fb24a6L34-R34): Renamed the constant `DATE_OF_BIRTH_KEY` from `"dateOfBirth"` to `"birthday"` to match Facebook's API naming convention.
* [`integrations/facebook/src/test/kotlin/com/rudderstack/integration/kotlin/facebook/FacebookIn …
=> fix: update dob key in facebook integration

sonar-project.properties
This pull request updates the `sonar-project.properties` file to improve SonarCloud analysis settings by excluding test files from the analysis.
* [`sonar-project.properties`](diffhunk://#diff-43ed9d31bea2a6d518d69836bcd1a8e6bd81bf4df96c4745792c220ca5aa549cR12-R13): Added `sonar.exclusions` to exclude test files located in `**/src/test/**` and `integrations/*/src/test/**` from SonarCloud analysis.
We don't want sonar cloud to analyse our test files since they don't follow same coding conventions.
=> chore: update sonar properties to exclude test files from analysis

buildSrc/src/main/kotlin/RudderStackBuildConfig.kt
Back-merge PR for Firebase and AppsFlyer integrations.
=> chore: firebase and appsflyer release back merge to develop

.github/workflows/pr-validation.yml, scripts/send-slack-notification.sh
Fix PR validation Slack notifications to accurately reflect the overall workflow status. Previously, the workflow would send misleading "success" notifications to Slack even when critical validation jobs like PR title check or SonarCloud analysis failed.
**Problem:** The `build-check` job (which sent Slack notifications) only depended on some validation jobs and did NOT depend on `pr-title-check` and `sonarcloud-analysis`. This caused incorrect "✅ PR Validation passed" messages even when key validations failed.
**Solution:** Updated job dependencies and moved Slack notification logic to the `pr-validation-summary` job, which properly depends on ALL validation jobs and provides detailed failure information.
- Updated `build-check` job to depend on ALL validation jobs: `[pr-title-check, …
=> ci: merge updated GitHub workflow to main

README.md
This pull request adds a new integration to the documentation. The most important change is the addition of the AppsFlyer integration to the list of available integrations in the `README.md` file.
-  Added AppsFlyer to the list of available integrations in `README.md`, allowing users to send event data to AppsFlyer for analytics.
=> docs(readme): update for appsflyer integration

buildSrc/src/main/kotlin/RudderStackBuildConfig.kt
This PR reverts the version name and version code change which were mistakenly updated in [this](https://github.com/rudderlabs/rudder-sdk-kotlin/pull/215) PR.
=> chore: revert unintended version and build number bump
